language: python
python:
  - "2.7"
install:
  - "pip install -r requirements_tests.txt"
  - "pip install python-coveralls"
  - "python setup.py develop"
script:
  - "nosetests --with-doctest --doctest-extension=rst --with-cov --cover-erase --cov-config .coveragerc --cov-report term-missing"
after_success:
  - "coveralls"